### ISSUE TITLE
Parsing error in zsh on MacOS

### ISSUE THREAD

**Issue by isaacwasserman** [rikhuijzer/ata#36]
When using inside of zsh in the standard MacOS terminal application, submitting a prompt returns the error: `prompt::request failed with: EOF while parsing a string at line 1 column 148` (the exact numbers depend on the prompt). If I open in bash or sh, I have no issues. Additionally, if I open a nested instance of zsh inside zsh, I can run it without issues.

Environment:
MacOS: 14.2.1
zsh: 5.9
ata: 2.0.2

**Comment by rikhuijzer** [comment]
Hi @isaacwasserman. Due to the high amount of new GPT terminal applications that are being created (high amount of competitors), I decided to do other things, so I won't be maintaining this project or adding new features. 

Sorry for not putting this information in the README. I'll update the README now.

**Comment by rikhuijzer** [comment]
I cannot reproduce this. It might have been fixed in v2.0.3 due to updating to a newer [rustyline](https://github.com/kkawakam/rustyline) version.

**Comment by isaacwasserman** [comment]
Yes, 2.0.3 fixed it. Thanks.
